### ISSUE TITLE
503 errors terminate the bot

### ISSUE THREAD

**Issue by Stuart1998** [O-Gourari/reddit-streamable-bot#1]
`
2019-03-18 13:50:52,173 [ERROR] Unexpected error
Traceback (most recent call last):
  File "C:\Users\Stuart\Desktop\smashmirrorbot\bot.py", line 103, in <module>
    main()
  File "C:\Users\Stuart\Desktop\smashmirrorbot\bot.py", line 62, in main
    for submission in subreddit.stream.submissions(skip_existing=True):
  File "C:\Users\Stuart\AppData\Roaming\Python\Python37\site-packages\praw\models\util.py", line 168, in stream_generator
    limit=limit, params={'before': before_fullname}))):
  File "C:\Users\Stuart\AppData\Roaming\Python\Python37\site-packages\praw\models\listing\generator.py", line 52, in __next__
    self._next_batch()
  File "C:\Users\Stuart\AppData\Roaming\Python\Python37\site-packages\praw\models\listing\generator.py", line 62, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "C:\Users\Stuart\AppData\Roaming\Python\Python37\site-packages\praw\reddit.py", line 391, in get
    data = self.request('GET', path, params=params)
  File "C:\Users\Stuart\AppData\Roaming\Python\Python37\site-packages\praw\reddit.py", line 506, in request
    params=params)
  File "C:\Users\Stuart\AppData\Roaming\Python\Python37\site-packages\prawcore\sessions.py", line 185, in request
    params=params, url=url)
  File "C:\Users\Stuart\AppData\Roaming\Python\Python37\site-packages\prawcore\sessions.py", line 128, in _request_with_retries
    retries, saved_exception, url)
  File "C:\Users\Stuart\AppData\Roaming\Python\Python37\site-packages\prawcore\sessions.py", line 94, in _do_retry
    params=params, url=url, retries=retries - 1)
  File "C:\Users\Stuart\AppData\Roaming\Python\Python37\site-packages\prawcore\sessions.py", line 128, in _request_with_retries
    retries, saved_exception, url)
  File "C:\Users\Stuart\AppData\Roaming\Python\Python37\site-packages\prawcore\sessions.py", line 94, in _do_retry
    params=params, url=url, retries=retries - 1)
  File "C:\Users\Stuart\AppData\Roaming\Python\Python37\site-packages\prawcore\sessions.py", line 130, in _request_with_retries
    raise self.STATUS_EXCEPTIONS[response.status_code](response)
prawcore.exceptions.ServerError: received 503 HTTP response
`

503 errors should result in a graceful failure, retrying after some time rather than terminating the bot process.

**Comment by Stuart1998** [comment]
Or was this already fixed in between the last version and the current one? Is there a changelog?
